apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-backend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/hostname: app.martianov.devops7.test-danit.com
spec:
  ingressClassName: nginx
  rules:
    - host: app.martianov.devops7.test-danit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: application-backend
                port:
                  number: 80